### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_key'

### ISSUE THREAD

**Issue by ldgarcia** [trivio/common_crawl_index#21]
Input:

``` bash
./bin/remote_copy check "org.domain.www"
```

Output:

``` bash
Traceback (most recent call last):
  File "./bin/remote_copy", line 152, in <module>
    mmap = BotoMap(s3_anon, src_bucket, '/common-crawl/projects/url-index/url-index.1356128792')
  File "./bin/remote_copy", line 35, in __init__
    self.key = bucket.get_key(key_name)
AttributeError: 'NoneType' object has no attribute 'get_key'
```

**Comment by jspacker** [comment]
./bin/remote_copy check "com.nytimes.blogs.fivethirtyeight"
works for me

do you get anything when you run `s3cmd ls s3://aws-publicdatasets/`?
